version: '3'
services:
  advanced_sql_mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    restart: always
    container_name: advanced_sql_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
  
  advanced_sql_postgres:
    image: postgres:9
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    container_name: advanced_sql_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1